controller_manager:
  ros__parameters:
    update_rate: 30
    # <!-- CHANGE ACCORDINLY -->
    #use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    # TOOD try change it
    # Odom average rate
    publish_rate: 50.0

    base_frame_id: base_link

    # left_wheel_names: ['left_wheel_joint']
    # right_wheel_names: ['right_wheel_joint']
    left_wheel_names: ['front_left_wheel_joint', 'rear_left_wheel_joint']
    right_wheel_names: ['front_right_wheel_joint', 'rear_right_wheel_joint']
    wheel_separation: 0.250
    wheel_radius: 0.05

    #use_stamped_vel: false

    # open_loop: false    

    wheels_per_side: 2
    #wheel_separation_multiplier: 1
    #left_wheel_radius_multiplier: 1
    #right_wheel_radius_multiplier: 1

    # odom_frame_id: x
    # pose_covariance_diagonal: x
    # twist_covariance_diagonal: x
    # open_loop: x
    # enable_odom_tf: x

    #cmd_vel_timeout: 0.5
    # publish_limited_velocity: x
    # velocity_rolling_window_size: x
    

    # linear.x.has_velocity_limits: false
    # linear.x.has_acceleration_limits: false
    # linear.x.has_jerk_limits: false
    # linear.x.max_velocity: NAN
    # linear.x.min_velocity: NAN
    # linear.x.max_acceleration: NAN
    # linear.x.min_acceleration: NAN
    # linear.x.max_jerk: NAN
    # linear.x.min_jerk: NAN

    # angular.z.has_velocity_limits: false
    # angular.z.has_acceleration_limits: false
    # angular.z.has_jerk_limits: false
    # angular.z.max_velocity: NAN
    # angular.z.min_velocity: NAN
    # angular.z.max_acceleration: NAN
    # angular.z.min_acceleration: NAN
    # angular.z.max_jerk: NAN
    # angular.z.min_jerk: NAN




# joint_broad:
#   ros__parameters: